name: Deploy
on:
  push:
    branch:
      - main
    paths-ignore: # 下列文件的变更不触发部署
      - .vscode
      - .eslintrc.cjs
      - .gitignore
      - .prettierrc.json
      - README.md
  repository_dispatch:
    types: rebuild

jobs:
  main-branch-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          port: ${{ secrets.PORT }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            cd /opt/cxs/todo
            git pull origin main
            pnpm install
            npm run build